### ISSUE TITLE
Cannot find BlockCommentExtension from Xcode menu

### ISSUE THREAD

**Issue by iwill** [superk589/BlockComment#1]
I installed BlockComment from AppStore, but cannot find BlockCommentExtension from Xcode menu, and also cannot find it from shortcuts setting.

Xcode: Version 8.3.3 (8E3004b)
macOS: 10.12.5

**Comment by superk589** [comment]
1. Run the application at lease once, then close it.
2. Go to System Preferences -> Extensions -> Xcode Source Editor and enable this extension
3. Reopen Xcode and you can find this extension from Xcode menu.
Please try as the above.

**Comment by superk589** [comment]
@iwill 是国人同行? 
我也只是初学者, 这是练手写的小项目, 以后多多交流, 多多指教

**Comment by iwill** [comment]
哈哈 是的 以前随便用插件时这个功能用得最多 刚才偶然在AppStore上看见 果断装了 👍

**Comment by iwill** [comment]
改了系统设置可以用了，不过貌似只支持整行的注释，建议参考下 CComment，支持注释 /* 选中文本 */ —— 哪怕只选中一行中间的几个字符，如果选中文本已经注释、再按快捷键会取消注释，那是我试过最好用的。

https://github.com/flexih/Xcode-CComment

**Comment by superk589** [comment]
好的 感谢建议 我会参考一下 
目前没考虑那么多, 个人习惯单行用//, 多行才用/* */方式
